-- Cog: Image Generation Pipeline
-- Database schema for Supabase

-- Series: collections of images with shared context
CREATE TABLE cog_series (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id UUID REFERENCES cog_series(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for nested series lookups
CREATE INDEX idx_cog_series_parent ON cog_series(parent_id);

-- Images: individual image files with metadata
CREATE TABLE cog_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  series_id UUID NOT NULL REFERENCES cog_series(id) ON DELETE CASCADE,
  job_id UUID, -- nullable, set when generated by a job
  storage_path TEXT NOT NULL, -- Supabase storage path
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'image/png',
  width INTEGER,
  height INTEGER,
  file_size INTEGER,
  source TEXT NOT NULL CHECK (source IN ('upload', 'generated')),
  prompt TEXT, -- generation prompt if applicable
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for series image lookups
CREATE INDEX idx_cog_images_series ON cog_images(series_id);
CREATE INDEX idx_cog_images_job ON cog_images(job_id);

-- Jobs: sequences of AI calls to generate images
CREATE TABLE cog_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  series_id UUID NOT NULL REFERENCES cog_series(id) ON DELETE CASCADE,
  title TEXT,
  base_prompt TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'ready', 'running', 'completed', 'failed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error_message TEXT
);

-- Add foreign key from images to jobs (after jobs table exists)
ALTER TABLE cog_images
  ADD CONSTRAINT fk_cog_images_job
  FOREIGN KEY (job_id) REFERENCES cog_jobs(id) ON DELETE SET NULL;

-- Index for series job lookups
CREATE INDEX idx_cog_jobs_series ON cog_jobs(series_id);
CREATE INDEX idx_cog_jobs_status ON cog_jobs(status);

-- Job steps: individual calls in a job sequence
CREATE TABLE cog_job_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES cog_jobs(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL,
  step_type TEXT NOT NULL CHECK (step_type IN ('llm', 'image_gen')),
  model TEXT NOT NULL, -- e.g., 'gemini-2.0-flash', 'imagen-3'
  prompt TEXT NOT NULL,
  context JSONB DEFAULT '{}', -- additional context for the step
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'skipped')),
  output JSONB, -- step output (text response, image URL, etc.)
  error_message TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for job step ordering
CREATE INDEX idx_cog_job_steps_job_seq ON cog_job_steps(job_id, sequence);

-- Updated_at trigger function (reuse if exists)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers
CREATE TRIGGER update_cog_series_updated_at
  BEFORE UPDATE ON cog_series
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_cog_jobs_updated_at
  BEFORE UPDATE ON cog_jobs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- RLS Policies (adjust based on auth requirements)
ALTER TABLE cog_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE cog_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE cog_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE cog_job_steps ENABLE ROW LEVEL SECURITY;

-- For now: allow all authenticated users (admin-only tool)
CREATE POLICY "Allow authenticated access to cog_series"
  ON cog_series FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated access to cog_images"
  ON cog_images FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated access to cog_jobs"
  ON cog_jobs FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated access to cog_job_steps"
  ON cog_job_steps FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Storage bucket for cog images (run in Supabase dashboard or via API)
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('cog-images', 'cog-images', false);
