#!/bin/bash
# SessionStart hook — bootstrap environment for Claude Code sessions
#
# Handles two environments:
#   Local dev:     .env.local exists on disk → read from file, export to CLAUDE_ENV_FILE
#   Cloud session: vars injected into shell by platform → write .env.local so MCP
#                  server's --env-file flag works, then export to CLAUDE_ENV_FILE
#
# Also ensures mcp/node_modules is installed so the MCP server can start.

set -e

# ── 1. Ensure .env.local exists ─────────────────────────────────────────────
#
# If the file is missing but the required vars are already in the shell
# environment (cloud session), synthesize .env.local from them.

ENV_FILE=".env.local"

if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -n "$NEXT_PUBLIC_SUPABASE_URL" && -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ]]; then
    # Cloud session: write .env.local from shell environment
    {
      echo "# Generated by session-init.sh from shell environment"
      for var in \
        NEXT_PUBLIC_SUPABASE_URL \
        NEXT_PUBLIC_SUPABASE_ANON_KEY \
        SUPABASE_SERVICE_ROLE_KEY \
        ANTHROPIC_API_KEY \
        OPENAI_API_KEY \
        GOOGLE_GENERATIVE_AI_API_KEY \
        NEXT_PUBLIC_SHOW_SPLASH \
        NODE_ENV; do
        [[ -n "${!var}" ]] && echo "$var=${!var}"
      done
    } > "$ENV_FILE"
  fi
fi

# ── 2. Export vars to CLAUDE_ENV_FILE ───────────────────────────────────────
#
# CLAUDE_ENV_FILE persists exported vars across Bash tool calls in the session.
# Only act if Claude Code provides this file.

if [[ -n "$CLAUDE_ENV_FILE" && -f "$ENV_FILE" ]]; then
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    case "$key" in
      NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|\
      ANTHROPIC_API_KEY|OPENAI_API_KEY|GOOGLE_GENERATIVE_AI_API_KEY|\
      NEXT_PUBLIC_SHOW_SPLASH|NODE_ENV)
        echo "export $key=\"$value\"" >> "$CLAUDE_ENV_FILE"
        ;;
    esac
  done < "$ENV_FILE"
fi

# ── 3. Ensure mcp/node_modules is installed ──────────────────────────────────
#
# The MCP server (mcp/dist/index.js) requires its own node_modules.
# In cloud sessions these won't be present after a fresh clone or checkout.

if [[ -f "mcp/package.json" && ! -d "mcp/node_modules" ]]; then
  npm install --prefix mcp --silent
fi

exit 0
