import { Item, Collection, Trip, PurchaseRequest } from './types';

// Sample data for development
export const sampleItems: Item[] = [
  {
    id: '1',
    name: 'REI Co-op Flash 55 Pack',
    description: 'Lightweight backpacking pack',
    brand: 'REI Co-op',
    model: 'Flash 55',
    weight: 1134, // grams
    price: 139,
    condition: 'good',
    category: 'Packs',
    tags: ['backpacking', 'lightweight', 'hiking'],
    status: 'available',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Big Agnes Copper Spur HV UL2',
    description: '2-person ultralight tent',
    brand: 'Big Agnes',
    model: 'Copper Spur HV UL2',
    weight: 1362,
    price: 450,
    condition: 'new',
    category: 'Shelter',
    tags: ['tent', 'ultralight', '2-person'],
    status: 'available',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Western Mountaineering UltraLite',
    description: '20°F down sleeping bag',
    brand: 'Western Mountaineering',
    model: 'UltraLite',
    weight: 794,
    price: 425,
    condition: 'good',
    category: 'Sleep System',
    tags: ['sleeping bag', 'down', '20F'],
    status: 'checked-out',
    currentTripId: '1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '4',
    name: 'Jetboil Flash',
    description: 'Personal cooking system',
    brand: 'Jetboil',
    model: 'Flash',
    weight: 415,
    price: 100,
    condition: 'good',
    category: 'Cooking',
    tags: ['stove', 'cooking', 'fast'],
    status: 'available',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
];

export const sampleCollections: Collection[] = [
  {
    id: '1',
    name: 'Ultralight Backpacking',
    description: 'Gear for ultralight backpacking trips',
    color: '#10b981',
    itemIds: ['1', '2', '3'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '2',
    name: 'Car Camping',
    description: 'Comfortable gear for car camping',
    color: '#3b82f6',
    itemIds: ['4'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const sampleTrips: Trip[] = [
  {
    id: '1',
    name: 'Olympic Peninsula Backpacking',
    description: '3-day backpacking trip in Olympic National Park',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-03-18'),
    location: 'Olympic National Park, WA',
    type: 'backpacking',
    status: 'active',
    checkedOutItems: [
      {
        itemId: '3',
        checkedOutAt: new Date('2024-03-01'),
      },
    ],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-01'),
  },
];

export const samplePurchaseRequests: PurchaseRequest[] = [
  {
    id: '1',
    name: 'Replacement Sleeping Bag',
    description: '20°F down sleeping bag to replace lost item',
    category: 'Sleep System',
    reason: 'lost',
    priority: 'urgent',
    status: 'pending',
    estimatedCost: 425,
    replacementFor: '3',
    triggerTripId: '1',
    notes: 'Lost during Olympic Peninsula trip checkout',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '2',
    name: 'Water Filter',
    description: 'Lightweight water filtration system',
    category: 'Water Treatment',
    reason: 'planning-gap',
    priority: 'high',
    status: 'pending',
    estimatedCost: 150,
    vendor: 'REI',
    notes: 'Needed for upcoming desert backpacking trips',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Lightweight Trekking Poles',
    description: 'Carbon fiber trekking poles',
    category: 'Tools',
    reason: 'new',
    priority: 'medium',
    status: 'approved',
    estimatedCost: 180,
    actualCost: 165,
    vendor: 'Black Diamond',
    orderNumber: 'BD-2024-001',
    orderDate: new Date('2024-02-25'),
    expectedDelivery: new Date('2024-03-05'),
    notes: 'For improved stability on technical terrain',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-25'),
  },
];