/** Body proportions basis shape keys — 12 atomic axes */
export default [
  {
    name: 'luv_torso_width',
    bones: ['DEF-spine.003', 'DEF-spine.004'],
    axis: [1, 0, 0],
    magnitude: 0.008,
    symmetric: false,
  },
  {
    name: 'luv_waist_width',
    bones: ['DEF-spine.001', 'DEF-spine.002'],
    axis: [1, 0, 0],
    magnitude: 0.008,
    symmetric: false,
  },
  {
    name: 'luv_chest_depth',
    bones: ['DEF-spine.004', 'DEF-spine.005'],
    axis: [0, 0, 1],
    magnitude: 0.006,
  },
  {
    name: 'luv_shoulder_width',
    bones: ['DEF-shoulder.L', 'DEF-shoulder.R'],
    axis: [1, 0, 0],
    magnitude: 0.008,
    symmetric: true,
  },
  {
    name: 'luv_hip_width',
    bones: ['DEF-pelvis.L', 'DEF-pelvis.R'],
    axis: [1, 0, 0],
    magnitude: 0.008,
    symmetric: true,
  },
  {
    name: 'luv_breast_size',
    bones: ['DEF-breast.L', 'DEF-breast.R'],
    axis: [1, 1, 1],
    magnitude: 0.008,
    useRadial: true,
  },
  {
    name: 'luv_breast_height',
    bones: ['DEF-breast.L', 'DEF-breast.R'],
    axis: [0, 1, 0],
    magnitude: 0.005,
  },
  {
    name: 'luv_thigh_width',
    bones: ['DEF-thigh.L', 'DEF-thigh.L.001', 'DEF-thigh.R', 'DEF-thigh.R.001'],
    axis: [1, 0, 0],
    magnitude: 0.006,
    symmetric: true,
  },
  {
    name: 'luv_calf_width',
    bones: ['DEF-shin.L', 'DEF-shin.L.001', 'DEF-shin.R', 'DEF-shin.R.001'],
    axis: [1, 0, 0],
    magnitude: 0.005,
    symmetric: true,
  },
  {
    name: 'luv_upper_arm_width',
    bones: ['DEF-upper_arm.L', 'DEF-upper_arm.L.001', 'DEF-upper_arm.R', 'DEF-upper_arm.R.001'],
    axis: [1, 0, 0],
    magnitude: 0.005,
    symmetric: true,
  },
  {
    name: 'luv_forearm_width',
    bones: ['DEF-forearm.L', 'DEF-forearm.L.001', 'DEF-forearm.R', 'DEF-forearm.R.001'],
    axis: [1, 0, 0],
    magnitude: 0.004,
    symmetric: true,
  },
  {
    name: 'luv_overall_mass',
    bones: ['DEF-spine', 'DEF-spine.001', 'DEF-spine.002', 'DEF-spine.003',
      'DEF-spine.004', 'DEF-spine.005', 'DEF-spine.006',
      'DEF-pelvis.L', 'DEF-pelvis.R',
      'DEF-thigh.L', 'DEF-thigh.R', 'DEF-shin.L', 'DEF-shin.R',
      'DEF-upper_arm.L', 'DEF-upper_arm.R', 'DEF-forearm.L', 'DEF-forearm.R'],
    axis: [1, 1, 1],
    magnitude: 0.006,
    useRadial: true,
  },
];
