/** Eyes + brows basis shape keys — 12 atomic axes */
export default [
  {
    name: 'luv_eye_width',
    bones: ['DEF-lower_eye.001.L', 'DEF-lower_eye.001.R', 'DEF-lower_eye.003.L', 'DEF-lower_eye.003.R',
      'DEF-upper_eye_lid.001.L', 'DEF-upper_eye_lid.001.R', 'DEF-upper_eye_lid.003.L', 'DEF-upper_eye_lid.003.R'],
    axis: [1, 0, 0],
    magnitude: 0.003,
    symmetric: true,
  },
  {
    name: 'luv_eye_height',
    bones: ['DEF-upper_eye_lid.001.L', 'DEF-upper_eye_lid.002.L', 'DEF-upper_eye_lid.003.L',
      'DEF-upper_eye_lid.001.R', 'DEF-upper_eye_lid.002.R', 'DEF-upper_eye_lid.003.R'],
    axis: [0, 1, 0],
    magnitude: 0.003,
  },
  {
    name: 'luv_eye_tilt',
    bones: ['DEF-upper_eye_lid.003.L', 'DEF-upper_eye_lid.003.R',
      'DEF-lower_eye_lid.003.L', 'DEF-lower_eye_lid.003.R'],
    axis: [0, 1, 0],
    magnitude: 0.003,
  },
  {
    name: 'luv_eye_depth',
    bones: ['DEF-eye.L', 'DEF-eye.R'],
    axis: [0, 0, 1],
    magnitude: 0.004,
  },
  {
    name: 'luv_eye_spacing',
    bones: ['DEF-eye.L', 'DEF-eye.R',
      'DEF-upper_eye_lid.001.L', 'DEF-upper_eye_lid.002.L', 'DEF-upper_eye_lid.003.L',
      'DEF-upper_eye_lid.001.R', 'DEF-upper_eye_lid.002.R', 'DEF-upper_eye_lid.003.R',
      'DEF-lower_eye_lid.001.L', 'DEF-lower_eye_lid.002.L', 'DEF-lower_eye_lid.003.L',
      'DEF-lower_eye_lid.001.R', 'DEF-lower_eye_lid.002.R', 'DEF-lower_eye_lid.003.R'],
    axis: [1, 0, 0],
    magnitude: 0.004,
    symmetric: true,
  },
  {
    name: 'luv_eyelid_fold',
    bones: ['DEF-upper_eye_lid.001.L', 'DEF-upper_eye_lid.002.L', 'DEF-upper_eye_lid.003.L',
      'DEF-upper_eye_lid.001.R', 'DEF-upper_eye_lid.002.R', 'DEF-upper_eye_lid.003.R'],
    axis: [0, 0, -1],
    magnitude: 0.002,
  },
  {
    name: 'luv_eyelid_crease_height',
    bones: ['DEF-upper_eye_squeeze.L', 'DEF-upper_eye_squeeze.R'],
    axis: [0, 1, 0],
    magnitude: 0.003,
  },
  {
    name: 'luv_brow_height',
    bones: ['DEF-brow.001.L', 'DEF-brow.002.L', 'DEF-brow.003.L',
      'DEF-brow.001.R', 'DEF-brow.002.R', 'DEF-brow.003.R',
      'DEF-brow_upper.001.L', 'DEF-brow_upper.002.L', 'DEF-brow_upper.003.L',
      'DEF-brow_upper.001.R', 'DEF-brow_upper.002.R', 'DEF-brow_upper.003.R'],
    axis: [0, 1, 0],
    magnitude: 0.004,
  },
  {
    name: 'luv_brow_arch',
    bones: ['DEF-brow.002.L', 'DEF-brow.002.R',
      'DEF-brow_upper.002.L', 'DEF-brow_upper.002.R'],
    axis: [0, 1, 0],
    magnitude: 0.003,
  },
  {
    name: 'luv_brow_thickness',
    bones: ['DEF-brow.001.L', 'DEF-brow.002.L', 'DEF-brow.003.L',
      'DEF-brow.001.R', 'DEF-brow.002.R', 'DEF-brow.003.R'],
    axis: [0, 0, 1],
    magnitude: 0.002,
  },
  {
    name: 'luv_brow_spacing',
    bones: ['DEF-brow.001.L', 'DEF-brow.001.R',
      'DEF-brow_upper.001.L', 'DEF-brow_upper.001.R'],
    axis: [1, 0, 0],
    magnitude: 0.003,
    symmetric: true,
  },
  {
    name: 'luv_brow_tilt',
    bones: ['DEF-brow.003.L', 'DEF-brow.003.R',
      'DEF-brow_upper.003.L', 'DEF-brow_upper.003.R'],
    axis: [0, 1, 0],
    magnitude: 0.003,
  },
];
