/**
 * Luv ↔ Cog Image Service Integration (Server-side)
 *
 * Server-side variant of cog-integration.ts using the service role client.
 * Used by generateLuvImage() and API routes that run in server context.
 */

import { createClient } from '../supabase-server';
import { createImageServer } from '../cog/server/images';
import type { CogImage, CogImageInsert } from '../types/cog';

const seriesCache = new Map<string, string>();

/**
 * Get or create a Luv series by its canonical key (server-side).
 */
export async function getLuvSeriesServer(key: string): Promise<string> {
  const cached = seriesCache.get(key);
  if (cached) return cached;

  const title = luvSeriesTitle(key);
  const client = await createClient();

  const { data: existing } = await (client as any)
    .from('cog_series')
    .select('id')
    .eq('title', title)
    .contains('tags', ['luv'])
    .limit(1)
    .maybeSingle();

  if (existing) {
    seriesCache.set(key, existing.id);
    return existing.id;
  }

  const { data: created, error } = await (client as any)
    .from('cog_series')
    .insert({
      title,
      description: luvSeriesDescription(key),
      tags: ['luv', ...luvSeriesTags(key)],
    })
    .select()
    .single();

  if (error) throw error;

  seriesCache.set(key, created.id);
  return created.id;
}

/**
 * Create a Luv image record in cog_images (server-side).
 */
export async function createLuvCogImageServer(opts: {
  seriesKey: string;
  storagePath: string;
  filename: string;
  mimeType: string;
  source: 'upload' | 'generated';
  prompt?: string;
  metadata?: Record<string, unknown>;
}): Promise<CogImage> {
  const seriesId = await getLuvSeriesServer(opts.seriesKey);

  return createImageServer({
    series_id: seriesId,
    storage_path: opts.storagePath,
    filename: opts.filename,
    mime_type: opts.mimeType,
    source: opts.source,
    prompt: opts.prompt,
    metadata: opts.metadata ?? {},
  });
}

// ---------------------------------------------------------------------------
// Series taxonomy (shared with client version)
// ---------------------------------------------------------------------------

function luvSeriesTitle(key: string): string {
  if (key === 'references') return 'Luv — References';
  if (key === 'generations') return 'Luv — Generations';
  if (key === 'reviews') return 'Luv — Reviews';
  if (key.startsWith('module:')) return `Luv — Module: ${key.slice(7)}`;
  if (key.startsWith('scene:')) return `Luv — Scene: ${key.slice(6)}`;
  return `Luv — ${key}`;
}

function luvSeriesDescription(key: string): string {
  if (key === 'references') return 'Canonical and reference images for Luv character consistency';
  if (key === 'generations') return 'Images generated by Luv agent during chat conversations';
  if (key === 'reviews') return 'Images uploaded for reinforcement review sessions';
  if (key.startsWith('module:')) return `Reference media for chassis module: ${key.slice(7)}`;
  if (key.startsWith('scene:')) return `Generated images for stage scene: ${key.slice(6)}`;
  return '';
}

function luvSeriesTags(key: string): string[] {
  if (key === 'references') return ['references'];
  if (key === 'generations') return ['generations'];
  if (key === 'reviews') return ['reviews'];
  if (key.startsWith('module:')) return ['chassis', 'module', key.slice(7)];
  if (key.startsWith('scene:')) return ['stage', 'scene', key.slice(6)];
  return [];
}
