/**
 * Luv ↔ Cog Image Service Integration (Client-side)
 *
 * Series association uses entity_links (not title/tag matching):
 *   entity_links: source_type='luv', source_id=key, target_type='cog_series'
 *
 * Series taxonomy:
 *   - "chassis"      → one series for all chassis module media
 *   - "generations"   → images generated via chat agent
 *   - "references"    → canonical reference images
 */

import { supabase } from '../supabase';
import type { CogImage } from '../types/cog';
import { createSeries } from '../cog/series';
import { createImage, getCogImageUrl } from '../cog/images';
import { addTagToImage } from '../cog/tags';
import { generateThumbnails } from '../cog/thumbnails';

const seriesCache = new Map<string, string>();

/**
 * Resolve a Luv series key to its cog_series ID via entity_links.
 * Module keys (module:face) all resolve to the 'chassis' series.
 */
export async function getLuvSeries(key: string): Promise<string> {
  const resolvedKey = key.startsWith('module:') ? 'chassis' : key;

  const cached = seriesCache.get(resolvedKey);
  if (cached) return cached;

  const title = luvSeriesTitle(resolvedKey);

  // Look up by title + luv tag
  const { data: existing } = await (supabase as any)
    .from('cog_series')
    .select('id')
    .eq('title', title)
    .contains('tags', ['luv'])
    .limit(1)
    .maybeSingle();

  let seriesId: string;

  if (existing) {
    seriesId = existing.id;
  } else {
    const series = await createSeries({
      title,
      description: luvSeriesDescription(resolvedKey),
      tags: ['luv', resolvedKey],
    });
    seriesId = series.id;
  }

  seriesCache.set(resolvedKey, seriesId);
  return seriesId;
}

/**
 * Create a Luv image in the appropriate Cog series.
 * If moduleSlug is provided, auto-tags with the module tag.
 */
export async function createLuvCogImage(opts: {
  seriesKey: string;
  file: Blob | Buffer;
  filename: string;
  storagePath: string;
  source: 'upload' | 'generated';
  prompt?: string;
  metadata?: Record<string, unknown>;
  moduleSlug?: string;
}): Promise<CogImage> {
  const seriesId = await getLuvSeries(opts.seriesKey);

  const { error: uploadError } = await supabase.storage
    .from('cog-images')
    .upload(opts.storagePath, opts.file, {
      contentType: inferMimeType(opts.filename),
      upsert: false,
    });

  if (uploadError) throw uploadError;

  const image = await createImage({
    series_id: seriesId,
    storage_path: opts.storagePath,
    filename: opts.filename,
    mime_type: inferMimeType(opts.filename),
    source: opts.source,
    prompt: opts.prompt,
    metadata: opts.metadata ?? {},
  });

  // Auto-tag with module tag if applicable
  if (opts.moduleSlug) {
    await resolveAndTagModule(image.id, opts.moduleSlug);
  }

  generateThumbnails(image.id, image.storage_path).catch((err) =>
    console.error('[luv-cog] Thumbnail generation failed:', err)
  );

  return image;
}

/**
 * Get the public URL for a Luv image stored in the cog-images bucket.
 */
export function getLuvImageUrl(storagePath: string): string {
  return getCogImageUrl(storagePath);
}


// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async function resolveAndTagModule(imageId: string, moduleSlug: string) {
  try {
    const { data: tag } = await (supabase as any)
      .from('cog_tags')
      .select('id')
      .eq('name', moduleSlug)
      .is('series_id', null)
      .limit(1)
      .maybeSingle();

    if (tag) {
      await addTagToImage(imageId, tag.id);
    }
  } catch (err) {
    console.error('[luv-cog] Auto-tag failed:', err);
  }
}

function luvSeriesTitle(key: string): string {
  if (key === 'chassis') return 'Luv — Chassis';
  if (key === 'references') return 'Luv — References';
  if (key === 'generations') return 'Luv — Generations';
  if (key.startsWith('scene:')) return `Luv — Scene: ${key.slice(6)}`;
  return `Luv — ${key}`;
}

function luvSeriesDescription(key: string): string {
  if (key === 'chassis') return 'Reference media for all chassis modules';
  if (key === 'references') return 'Canonical and reference images for Luv character consistency';
  if (key === 'generations') return 'Images generated by Luv agent during chat conversations';
  if (key.startsWith('scene:')) return `Generated images for stage scene: ${key.slice(6)}`;
  return '';
}

function inferMimeType(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase();
  const mimeMap: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    webp: 'image/webp',
    gif: 'image/gif',
  };
  return mimeMap[ext ?? ''] ?? 'image/png';
}
