/**
 * Luv ↔ Cog Image Service Integration
 *
 * Provides series provisioning and image helpers for Luv to use Cog's
 * image infrastructure. Series are lazily created on first use and
 * cached for the session.
 *
 * Series taxonomy:
 *   - "Luv — References"         canonical/variation/training reference images
 *   - "Luv — Generations"        images generated via chat agent tool
 *   - "Luv — Module: {name}"     per-chassis-module reference media
 *   - "Luv — Scene: {name}"      per-stage-scene generations (future)
 */

import { supabase } from '../supabase';
import type { CogSeries, CogImage } from '../types/cog';
import { createSeries } from '../cog/series';
import { createImage, getCogImageUrl } from '../cog/images';
import { generateThumbnails } from '../cog/thumbnails';
import type { CogImageInsert } from '../types/cog';

// In-memory cache of resolved series IDs (per browser session)
const seriesCache = new Map<string, string>();

/**
 * Get or create a Luv series by its canonical key.
 * Keys follow the pattern: "references", "generations", "module:{slug}", "scene:{slug}"
 */
export async function getLuvSeries(key: string): Promise<string> {
  const cached = seriesCache.get(key);
  if (cached) return cached;

  const title = luvSeriesTitle(key);

  // Look for existing series by title + luv tag
  const { data: existing } = await (supabase as any)
    .from('cog_series')
    .select('id')
    .eq('title', title)
    .contains('tags', ['luv'])
    .limit(1)
    .maybeSingle();

  if (existing) {
    seriesCache.set(key, existing.id);
    return existing.id;
  }

  // Create new series
  const series = await createSeries({
    title,
    description: luvSeriesDescription(key),
    tags: ['luv', ...luvSeriesTags(key)],
  });

  seriesCache.set(key, series.id);
  return series.id;
}

/**
 * Create a Luv image in the appropriate Cog series.
 * Handles storage upload and cog_images record creation.
 */
export async function createLuvCogImage(opts: {
  seriesKey: string;
  file: Blob | Buffer;
  filename: string;
  storagePath: string;
  source: 'upload' | 'generated';
  prompt?: string;
  metadata?: Record<string, unknown>;
}): Promise<CogImage> {
  const seriesId = await getLuvSeries(opts.seriesKey);

  // Upload to cog-images bucket (shared with Cog)
  const { error: uploadError } = await supabase.storage
    .from('cog-images')
    .upload(opts.storagePath, opts.file, {
      contentType: inferMimeType(opts.filename),
      upsert: false,
    });

  if (uploadError) throw uploadError;

  // Create cog_images record
  const image = await createImage({
    series_id: seriesId,
    storage_path: opts.storagePath,
    filename: opts.filename,
    mime_type: inferMimeType(opts.filename),
    source: opts.source,
    prompt: opts.prompt,
    metadata: opts.metadata ?? {},
  });

  // Generate thumbnails in background (non-blocking)
  generateThumbnails(image.id, image.storage_path).catch((err) =>
    console.error('[luv-cog] Thumbnail generation failed:', err)
  );

  return image;
}

/**
 * Get the public URL for a Luv image stored in the cog-images bucket.
 */
export function getLuvImageUrl(storagePath: string): string {
  return getCogImageUrl(storagePath);
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function luvSeriesTitle(key: string): string {
  if (key === 'references') return 'Luv — References';
  if (key === 'generations') return 'Luv — Generations';
  if (key.startsWith('module:')) return `Luv — Module: ${key.slice(7)}`;
  if (key.startsWith('scene:')) return `Luv — Scene: ${key.slice(6)}`;
  return `Luv — ${key}`;
}

function luvSeriesDescription(key: string): string {
  if (key === 'references') return 'Canonical and reference images for Luv character consistency';
  if (key === 'generations') return 'Images generated by Luv agent during chat conversations';
  if (key.startsWith('module:')) return `Reference media for chassis module: ${key.slice(7)}`;
  if (key.startsWith('scene:')) return `Generated images for stage scene: ${key.slice(6)}`;
  return '';
}

function luvSeriesTags(key: string): string[] {
  if (key === 'references') return ['references'];
  if (key === 'generations') return ['generations'];
  if (key.startsWith('module:')) return ['chassis', 'module', key.slice(7)];
  if (key.startsWith('scene:')) return ['stage', 'scene', key.slice(6)];
  return [];
}

function inferMimeType(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase();
  const mimeMap: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    webp: 'image/webp',
    gif: 'image/gif',
  };
  return mimeMap[ext ?? ''] ?? 'image/png';
}
