-- Survey Tool Tables
-- AI-powered project onboarding system that generates contextual questionnaires

-- Survey definitions generated by LLM
CREATE TABLE studio_surveys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES studio_projects(id) ON DELETE CASCADE,

  -- Survey metadata
  status TEXT NOT NULL DEFAULT 'pending',  -- pending, in_progress, completed, expired
  version INTEGER NOT NULL DEFAULT 1,

  -- Generated survey structure (JSONB contains full SurveyDefinition)
  questions JSONB NOT NULL,

  -- Generation context (what LLM used to generate)
  generation_context JSONB NOT NULL,  -- { name, description, temperature, ... }
  generation_model TEXT NOT NULL,

  -- Completion tracking
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  current_question_index INTEGER DEFAULT 0,

  -- Processing status for artifact generation
  processing_status TEXT,  -- null, processing, completed, failed
  processing_started_at TIMESTAMPTZ,
  processing_completed_at TIMESTAMPTZ,
  processing_error TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(project_id, version),

  -- Constraints
  CONSTRAINT valid_status CHECK (status IN ('pending', 'in_progress', 'completed', 'expired')),
  CONSTRAINT valid_processing_status CHECK (
    processing_status IS NULL OR
    processing_status IN ('processing', 'completed', 'failed')
  )
);

-- Survey responses (one row per question answered)
CREATE TABLE studio_survey_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_id UUID NOT NULL REFERENCES studio_surveys(id) ON DELETE CASCADE,
  question_id TEXT NOT NULL,  -- Matches question.id in JSONB

  -- Response data
  response_value JSONB NOT NULL,  -- Flexible: string, array, object depending on question type
  response_text TEXT,  -- Denormalized text representation for search/display

  -- Metadata
  skipped BOOLEAN DEFAULT false,
  time_spent_seconds INTEGER,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(survey_id, question_id)
);

-- Track generated artifacts from survey completion
CREATE TABLE studio_survey_artifacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_id UUID NOT NULL REFERENCES studio_surveys(id) ON DELETE CASCADE,

  -- What was generated
  artifact_type TEXT NOT NULL,  -- hypothesis, experiment, customer_profile, assumption, project_field
  artifact_id UUID,  -- FK to the created entity (null for project_field updates)
  artifact_field TEXT,  -- For project_field type: which field was populated

  -- Generation details
  source_questions TEXT[],  -- Which question IDs informed this artifact
  confidence_score NUMERIC(3,2),  -- 0-1 how confident LLM was

  -- User actions
  user_accepted BOOLEAN,  -- null = not reviewed, true = accepted, false = rejected
  user_modified BOOLEAN DEFAULT false,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT valid_artifact_type CHECK (
    artifact_type IN ('hypothesis', 'experiment', 'customer_profile', 'assumption', 'project_field', 'bmc')
  ),
  CONSTRAINT valid_confidence_score CHECK (
    confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)
  )
);

-- Indexes for performance
CREATE INDEX idx_studio_surveys_project ON studio_surveys(project_id);
CREATE INDEX idx_studio_surveys_status ON studio_surveys(status);
CREATE INDEX idx_studio_surveys_processing_status ON studio_surveys(processing_status) WHERE processing_status IS NOT NULL;
CREATE INDEX idx_survey_responses_survey ON studio_survey_responses(survey_id);
CREATE INDEX idx_survey_artifacts_survey ON studio_survey_artifacts(survey_id);
CREATE INDEX idx_survey_artifacts_type ON studio_survey_artifacts(artifact_type);
CREATE INDEX idx_survey_artifacts_id ON studio_survey_artifacts(artifact_id) WHERE artifact_id IS NOT NULL;

-- Add user_id column to studio_projects for ownership tracking
-- This enables RLS policies
ALTER TABLE studio_projects
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- Set default user_id for existing projects (first user in system)
-- In production, this should be updated manually or via a data migration
UPDATE studio_projects
SET user_id = (SELECT id FROM auth.users LIMIT 1)
WHERE user_id IS NULL;

-- Make user_id NOT NULL after populating existing rows
ALTER TABLE studio_projects
ALTER COLUMN user_id SET NOT NULL;

-- Add columns to studio_projects for survey tracking
ALTER TABLE studio_projects
ADD COLUMN IF NOT EXISTS has_pending_survey BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS survey_generated_at TIMESTAMPTZ;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_studio_projects_user ON studio_projects(user_id);
CREATE INDEX idx_studio_projects_pending_survey ON studio_projects(has_pending_survey) WHERE has_pending_survey = true;

-- RLS Policies
ALTER TABLE studio_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE studio_survey_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE studio_survey_artifacts ENABLE ROW LEVEL SECURITY;

-- Users can only access their own surveys (through project ownership)
CREATE POLICY "Users can view their own surveys"
  ON studio_surveys FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM studio_projects
      WHERE studio_projects.id = studio_surveys.project_id
      AND studio_projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their own surveys"
  ON studio_surveys FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM studio_projects
      WHERE studio_projects.id = studio_surveys.project_id
      AND studio_projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their own surveys"
  ON studio_surveys FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM studio_projects
      WHERE studio_projects.id = studio_surveys.project_id
      AND studio_projects.user_id = auth.uid()
    )
  );

-- Survey responses policies
CREATE POLICY "Users can view their own survey responses"
  ON studio_survey_responses FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM studio_surveys
      JOIN studio_projects ON studio_projects.id = studio_surveys.project_id
      WHERE studio_surveys.id = studio_survey_responses.survey_id
      AND studio_projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their own survey responses"
  ON studio_survey_responses FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM studio_surveys
      JOIN studio_projects ON studio_projects.id = studio_surveys.project_id
      WHERE studio_surveys.id = studio_survey_responses.survey_id
      AND studio_projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their own survey responses"
  ON studio_survey_responses FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM studio_surveys
      JOIN studio_projects ON studio_projects.id = studio_surveys.project_id
      WHERE studio_surveys.id = studio_survey_responses.survey_id
      AND studio_projects.user_id = auth.uid()
    )
  );

-- Survey artifacts policies
CREATE POLICY "Users can view their own survey artifacts"
  ON studio_survey_artifacts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM studio_surveys
      JOIN studio_projects ON studio_projects.id = studio_surveys.project_id
      WHERE studio_surveys.id = studio_survey_artifacts.survey_id
      AND studio_projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Service role can manage survey artifacts"
  ON studio_survey_artifacts FOR ALL
  USING (auth.jwt() ->> 'role' = 'service_role')
  WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

-- Add helpful comments
COMMENT ON TABLE studio_surveys IS 'AI-generated surveys for project onboarding';
COMMENT ON TABLE studio_survey_responses IS 'User responses to survey questions';
COMMENT ON TABLE studio_survey_artifacts IS 'Tracks artifacts generated from survey responses';
COMMENT ON COLUMN studio_surveys.questions IS 'JSONB containing full SurveyDefinition with questions array';
COMMENT ON COLUMN studio_surveys.generation_context IS 'Input data used to generate the survey';
COMMENT ON COLUMN studio_survey_responses.response_text IS 'Denormalized text for search and display';
COMMENT ON COLUMN studio_survey_artifacts.confidence_score IS 'LLM confidence score (0-1) for generated artifact';
