-- Evolve luv_chassis_studies for the chassis study image generation pipeline.
-- Studies become multi-module, goal-driven image gen sessions where a Gemini
-- thinking subagent shapes a brief, then hands off to Gemini image gen.
-- Luv records satisfaction feedback on results.

-- Add new columns for the image gen pipeline
ALTER TABLE luv_chassis_studies
  ADD COLUMN IF NOT EXISTS module_slugs text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS goal text,
  ADD COLUMN IF NOT EXISTS style text,
  ADD COLUMN IF NOT EXISTS dynamics text,
  ADD COLUMN IF NOT EXISTS user_prompt text,
  ADD COLUMN IF NOT EXISTS brief jsonb,
  ADD COLUMN IF NOT EXISTS generation_prompt text,
  ADD COLUMN IF NOT EXISTS reference_image_paths text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS generated_image_path text,
  ADD COLUMN IF NOT EXISTS cog_image_id uuid REFERENCES cog_images(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS generation_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS feedback jsonb,
  ADD COLUMN IF NOT EXISTS aspect_ratio text NOT NULL DEFAULT '3:4',
  ADD COLUMN IF NOT EXISTS image_size text NOT NULL DEFAULT '2K',
  ADD COLUMN IF NOT EXISTS model text NOT NULL DEFAULT 'nano-banana-pro';

-- Expand status to cover pipeline stages
ALTER TABLE luv_chassis_studies DROP CONSTRAINT IF EXISTS luv_chassis_studies_status_check;
ALTER TABLE luv_chassis_studies ADD CONSTRAINT luv_chassis_studies_status_check
  CHECK (status IN ('briefing', 'generating', 'completed', 'failed', 'in_progress'));

-- Index for querying by module slugs (GIN for array containment)
CREATE INDEX IF NOT EXISTS idx_chassis_studies_module_slugs
  ON luv_chassis_studies USING GIN (module_slugs);

COMMENT ON COLUMN luv_chassis_studies.module_slugs IS 'Chassis module slugs this study focuses on';
COMMENT ON COLUMN luv_chassis_studies.goal IS 'What the study aims to explore or validate';
COMMENT ON COLUMN luv_chassis_studies.style IS 'Visual style direction (e.g. "soft natural light", "editorial portrait")';
COMMENT ON COLUMN luv_chassis_studies.dynamics IS 'Dynamic qualities to capture (e.g. "wind in hair", "subtle smile")';
COMMENT ON COLUMN luv_chassis_studies.user_prompt IS 'Original natural language prompt from user';
COMMENT ON COLUMN luv_chassis_studies.brief IS 'Structured brief generated by Gemini thinking subagent';
COMMENT ON COLUMN luv_chassis_studies.generation_prompt IS 'Final honed prompt passed to image gen model';
COMMENT ON COLUMN luv_chassis_studies.reference_image_paths IS 'Supabase storage paths of canonical images used as i2i bolsters';
COMMENT ON COLUMN luv_chassis_studies.generated_image_path IS 'Storage path of the generated study image';
COMMENT ON COLUMN luv_chassis_studies.cog_image_id IS 'FK to cog_images for the generated image';
COMMENT ON COLUMN luv_chassis_studies.generation_metadata IS 'Pipeline metadata: timings, model, tokens, thinking chain';
COMMENT ON COLUMN luv_chassis_studies.feedback IS 'User/agent satisfaction feedback on the generated image';
